// <auto-generated />
using System;
using KAIS.Interactive.DSPC_EXPLORER.Infrastructure.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KAIS.Interactive.DSPC_EXPLORER.Infrastructure.Migrations
{
    [DbContext(typeof(DSPC_ExplorerDbContext))]
    [Migration("20200413022338_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KAIS.Interactive.DSPC_EXPLORER.Infrastructure.Model.GraveOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GraveDepth");

                    b.Property<bool>("GraveHeadStone");

                    b.Property<string>("GraveLocation");

                    b.Property<string>("GraveOwnerAddress");

                    b.Property<string>("GraveOwnerName");

                    b.Property<string>("GraveReferenceCode");

                    b.Property<int>("GraveRow");

                    b.Property<string>("GraveSize");

                    b.Property<string>("JkIndex");

                    b.Property<string>("Remarks");

                    b.Property<int>("SectionId");

                    b.Property<string>("SubId");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("GraveOwners");
                });

            modelBuilder.Entity("KAIS.Interactive.DSPC_EXPLORER.Infrastructure.Model.Registrar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalComments");

                    b.Property<int>("Age");

                    b.Property<string>("AgeDetail");

                    b.Property<string>("BookPage");

                    b.Property<DateTime>("BurialDate");

                    b.Property<DateTime>("DeathDate");

                    b.Property<string>("DeathLocation");

                    b.Property<string>("FirstName");

                    b.Property<int?>("GraveOwnerId");

                    b.Property<string>("InternmentSignature");

                    b.Property<string>("LastName");

                    b.Property<string>("MarriageStatus");

                    b.Property<int>("NumberInBook");

                    b.Property<string>("NumberInfo");

                    b.Property<string>("Occupation");

                    b.Property<string>("Proprietary");

                    b.Property<string>("Public");

                    b.Property<string>("RegistrarName");

                    b.Property<string>("Religion");

                    b.Property<string>("SectionInfo");

                    b.Property<string>("Sex");

                    b.HasKey("Id");

                    b.HasIndex("GraveOwnerId");

                    b.ToTable("Registrars");
                });

            modelBuilder.Entity("KAIS.Interactive.DSPC_EXPLORER.Infrastructure.Model.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<DateTime>("DateOpened");

                    b.Property<int>("GraveCount");

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("KAIS.Interactive.DSPC_EXPLORER.Infrastructure.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovalPassword");

                    b.Property<string>("Password");

                    b.Property<int>("Type");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KAIS.Interactive.DSPC_EXPLORER.Infrastructure.Model.GraveOwner", b =>
                {
                    b.HasOne("KAIS.Interactive.DSPC_EXPLORER.Infrastructure.Model.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KAIS.Interactive.DSPC_EXPLORER.Infrastructure.Model.Registrar", b =>
                {
                    b.HasOne("KAIS.Interactive.DSPC_EXPLORER.Infrastructure.Model.GraveOwner", "GraveOwner")
                        .WithMany()
                        .HasForeignKey("GraveOwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
